### ISSUE TITLE
In-Client submission of bug reports and feedback

### ISSUE THREAD

**Issue by tauSentry** [MechWarriorOnline/issue-tracker#1]
* [How To Upvote This Issue](https://github.com/MechWarriorOnline/issue-tracker/wiki/How-To-Upvote-An-Issue)

---

Add a feature in the client that allows users to submit bug reports and feedback *instead* of having to send emails to feedback@mwomercs.com, or posting on the forum. This would eliminate the (small but sufficiently-annoying) hurdle that causes many players to not share bugs that they observe, and to not share friendly suggestions that they would like to see.

Currently, only the most vocal users post on Twitter, or the forums, or on the subreddits. Many voices are potentially not being heard. In-Client feedback might go a long way to addressing this, thereby getting a more representative cross-section of the MWO player-base.

**Comment by Tarogato-MWO** [comment]
I would suggest against this... this would require PGI to devise a system to handle a massive influx of small feedback tidbits, including sorting and categorisation. I would rather see something like this github project pick up that kind of slack and bring attention to small issues.

**Comment by tauSentry** [comment]
@Tarogato-MWO, that's a valid point. I would be totally cool with this issue-tracker picking up the slack on that.

**Comment by tauSentry** [comment]
After some consideration and out-of-channel discussion with other users, I have concluded that @Tarogato-MWO is absolutely correct. I am withdrawing my proposal and closing this issue.
