### ISSUE TITLE
Preset graphic settings cause major issues

### ISSUE THREAD

**Issue by DragonWrangler** [MechWarriorOnline/issue-tracker#120]
Every time I play MWO on a fresh install without touching the graphics settings there is a serious bug in which textures and assets fail to load. In no case is it playable, a few examples are on HPG the entire main area of the map fails to load and exists as a world hole that you can fall through, on frozen city the buildings are invisible and you can see through them but can not shoot through them, on crimson strait the tunnel exists in the same way as HPG's main area does, as a world hole that drops you out of the map. These issues can be fixed by increasing the graphics settings but that may not be possible for lower end machines or player not aware of the cause of the issue. My specs are Gtx 750 ti, 8 gigs of ram and an i5 4430.

**Comment by Tyler799** [comment]
Have you tried repairing the game? If on steam, you can just verify the game cache. If on MWO's launcher, I believe the repair tool is built-in.

**Comment by DragonWrangler** [comment]
Yes, I have verified the cache and used the repair tool for the standalone client. Neither of these fixed the issue, in the end I used the nvidia recommended settings and that fixed things. When I have some time I will post some screenshots.

**Comment by Tarogato-MWO** [comment]
I have experienced this issue when I had multithreading disabled in my user.cfg file. Could you verify that you are not using a user.cfg?

**Comment by tauSentry** [comment]
Administrivia...  

Doing another round of cleanup on issues where the OP hasn't responded to "Requesting More Info". Will re-open if he/she does.
