### ISSUE TITLE
Mechlab UI: Mech-stat popups hang with fast mouse movements

### ISSUE THREAD

**Issue by EricDunning** [MechWarriorOnline/issue-tracker#129]
* [How To Upvote This Issue](https://github.com/MechWarriorOnline/issue-tracker/wiki/How-To-Upvote-An-Issue)
* [When To Add A Comment To An Issue (vs Just Upvoting)](https://github.com/MechWarriorOnline/issue-tracker/wiki/When-To-Add-A-Comment-To-An-Issue)

---
When you pass your mouse quickly over the mech stats paper doll sections the popups that occur will hang on the UI. They will persist on the screen as long as you remain within the mechlab and will be removed by either passing your mouse back over a paper doll section or leaving the mechlab.

![mwo 06 05 2017-10 33 49](https://cloud.githubusercontent.com/assets/25422930/26795436/807bcee6-49da-11e7-9deb-0c863d680756.jpg)

**_Additional images provided by @TheEmperorOfMankind in #168._**
[Proof1](https://i.imgur.com/5h1kIfl.jpg)
[Proof2](https://i.imgur.com/6xDiBoq.png)
[Proof3](https://i.imgur.com/2acqIaK.jpg)

**Comment by tauSentry** [comment]
Administrivia...
Can you include a screenshot too.

**Comment by EricDunning** [comment]
![mwo 06 05 2017-10 33 49](https://cloud.githubusercontent.com/assets/25422930/26795436/807bcee6-49da-11e7-9deb-0c863d680756.jpg)

**Comment by IcebergTitanic** [comment]
It happens when you have the paperdoll expanded from the MechStats window. The orphaned windows are from the mouseovers on the various mech locations showing the info for that location, such as arm, leg, torso, etc. Moving mouse quickly off of that location or across another location seems to orphan the info window and you can't get rid of it except by going back and slowly mousing over a location again and then back off.

**Comment by Tarogato-MWO** [comment]
YES PLEASE THIS DRIVES ME NUTS. One time had one pop up right over a button I needed to click and I couldn't click it until I got out of the mechlab to force it to go away. Thank you for posting this, kana.

**Comment by tauSentry** [comment]
Update:  
According to the [release notes for Patch 1.4.132 (17-Oct-2017)](https://mwomercs.com/news/2017/10/1910-patch-notes-14132-17oct2017), this bug has been tackled.
