### ISSUE TITLE
Scroll through chat

### ISSUE THREAD

**Issue by colouredmirrorball** [MechWarriorOnline/issue-tracker#134]
PgUp and PgDwn used to scroll through the chat but that feature appears to have been broken in an update.

Cross Link: #29

**Comment by tauSentry** [comment]
Hi there @colouredmirrorball,
Check out [this thread](https://www.reddit.com/r/OutreachHPG/comments/6dknfp/psa_chat_scrolling) by So1ahma on the OutreachHPG subreddit from a few weeks back. It explains how those keys were reassigned by PGI for new features. You'll have to go into your keyboard settings to reset them how you like them.

Closing issue.

**Comment by colouredmirrorball** [comment]
Oh that is so obvious, thanks @tauSentry!

**Comment by tauSentry** [comment]
<o  Glad I could help!

Now get out there and pistol-whip everyone on your Friends List until they come here and vote on the issues they care about. :)
It's for their own good!
