### ISSUE TITLE
Call to arms popup displays or lingers when in map/game mode selection screen in quick play

### ISSUE THREAD

**Issue by colouredmirrorball** [MechWarriorOnline/issue-tracker#136]
* [How To Upvote This Issue](https://github.com/MechWarriorOnline/issue-tracker/wiki/How-To-Upvote-An-Issue)
* [When To Add A Comment To An Issue (vs Just Upvoting)](https://github.com/MechWarriorOnline/issue-tracker/wiki/When-To-Add-A-Comment-To-An-Issue)

---

Clicking on it results in you being taken to the faction play screen. This could only be a minor nuisance, but there are no more game navigation buttons! There is no way to return to the QP match except alt+F4 and restarting the game. 

EDIT...  
Screenshot (missing top-bar):  
https://steamuserimages-a.akamaihd.net/ugc/859474716370048335/502373BFF8732BDF4FA8E4A2D8153999C3B90599/

**Comment by tauSentry** [comment]
Administrivia...
Can you include a screenshot of this.

**Comment by colouredmirrorball** [comment]
I'll try but it's not easy to reproduce.

**Comment by colouredmirrorball** [comment]
I managed to reproduce the error and grabbed some screenshots

How to reproduce: 

 * Wait for a call to arms popup to appear
 * Click on Quick play
 * When a match is found, the call to arms popup is still visible on the map/mode selection screen (bug 1)
 * Click on it
 * You are taken to the faction play screen but there are no navigation buttons, the only options are to join a faction play match or alt+f4 out of the game

https://steamuserimages-a.akamaihd.net/ugc/859474716370048335/502373BFF8732BDF4FA8E4A2D8153999C3B90599/

**Comment by tauSentry** [comment]
Administrivia...  
Do you still experience this issue?

**Comment by colouredmirrorball** [comment]
Not recently. There have been few faction play popups due to the event lately though.

**Comment by tauSentry** [comment]
Administrivia...  
Doing some cleanup. Going to go ahead and close this issue. If it crops back up, I can reopen it.
