### ISSUE TITLE
Fix TAG vs ECM bug

### ISSUE THREAD

**Issue by rwil02** [MechWarriorOnline/issue-tracker#141]
There are I think 2 issues with TAG.
1 - OLD.  You can target a mech with TAG when it has ECM or is under ECM cover, and it works.
You CANNOT target a mech when it has ECM and is ALSO under ECM cover (or perhaps when under 2 lots of ECM cover).  Given it is a line of sight target designator, this is simply dumb.

~~2 - TAG should NOT give you "all the details" on a mech.  It used to be there was no choice about this.  But we now have UAVs, and a UAV lets you locate and target a mech, but not get "all the details".  TAG should work like a UAV targeting a single mech.  I suspect implementing this would fix the first issue anyway.~~
Edit: Item 2 will be moved to a separate feature request.

**Comment by tauSentry** [comment]
@Tarogato-MWO, can you weigh in on this one.

**Comment by Tarogato-MWO** [comment]
@tauSentry no I can't, I never use TAG, nor do I know or care how it's supposed to work. Sorry, =P

**Comment by tauSentry** [comment]
Hey @rwil02
So I rounded up some pilots so I could test point (1) in a private lobby.
Here was the setup.
Team 1: Me with TAG.
Team 2: ECM Mech A, ECM Mech B, Non-ECM Mech C.

A, B, and C are all grouped with 50m of each other.
I am positioned 600 meters away.

Result: I was able to successfully TAG and target each mech individually.

Was there any aspect that I may have missed in the testing? Or, did I misunderstand the bug description?

**Comment by rwil02** [comment]
Hmm.  I emailed a reply but it hasn't shown up.
Yes, that's what I would have done.

It's not a situation that arose very often, so I haven't seen it in months.
I haven't seen it mentioned in patch notes anywhere, but maybe I missed it, or it wasn't mentioned.
Maybe it got fixed as part of the skill tree rework?

**Comment by tauSentry** [comment]
@rwil02 
Roger that. In that case, I think for now what I'll do is close this issue and mark it "obsolete". *BUT* if it shows up again, you should definitely leave me an update under this issue and I'll re-open it.

For your other item (2), can you open up a separate feature-request for that one.

**Comment by tauSentry** [comment]
@rwil02
Also, if you see it happen again, try to get a screenshot of it so we have it here as a reference.
