### ISSUE TITLE
Unfairly given team damage timeout

### ISSUE THREAD

**Issue by rwil02** [MechWarriorOnline/issue-tracker#154]
Joined match.
People talking on VOIP at power up.
Got DC'd (as per other bug), as did at least one other person. #142 

Got back
Died in < 1 minute having never got near the rest of my team.
Lost 12:2
Got queue time out.
Because I apparently did 101 team damage.

**Comment by rwil02** [comment]
Hm.  This might be "incorrect match award"?

**Comment by tauSentry** [comment]
@rwil02, that certainly sounds like it could be yet another manifestation of the #152 bug.  
I recommend updating #152 with the description you provided here, and then afterwards I'll go ahead and close this issue.

**Comment by tauSentry** [comment]
Merged into #152
