### ISSUE TITLE
Add A Kill Counter To The MLX Cockpit

### ISSUE THREAD

**Issue by Larsh01** [MechWarriorOnline/issue-tracker#167]
* [How To Upvote This Issue](https://github.com/MechWarriorOnline/issue-tracker/wiki/How-To-Upvote-An-Issue)
* [When To Add A Comment To An Issue (vs Just Upvoting)](https://github.com/MechWarriorOnline/issue-tracker/wiki/When-To-Add-A-Comment-To-An-Issue)

---
The MLX is not the best mech in MWO, but is still a great little mech to use.  I've searched all over the cockpit, but have not found a kill counter.  Instead there is a mounted item on the right that looks like it would hold a kill counter.

Maybe it was taken back due to faulty wiring?

Proposal: Add kill-counter to the Mist Lynx cockpit.

**Comment by EricStork** [comment]
I would modify this to cover other Mechs.
Example, ever seen the Awesome's Kill Counter? Barely because most of it is hidden behind the mini-map center bottom.

**Comment by tauSentry** [comment]
According to the [Release Notes for Patch 1.4.143 (12-Dec-2017)](https://mwomercs.com/news/2017/12/1969-patch-notes-14143-12dec2017), this has been fixed.
