### ISSUE TITLE
Add option to hide/disable flash for Clan Chat

### ISSUE THREAD

**Issue by Tyler799** [MechWarriorOnline/issue-tracker#182]
Currently, the chat menu button constantly flashes due to clan chat. Since this isn't directly related to our unit or a message directly to us, it can be annoying that it's constantly flashing while in the mechlab. An option (say, by right clicking the button) to disable its updates/notifications would be nice.

**Comment by tauSentry** [comment]
Administrivia...  

For clarification, can you distinguish your proposal from the options in Settings:  

![notification options](https://user-images.githubusercontent.com/27810004/29751863-57f84e6c-8b08-11e7-98c6-f9a568618a0d.png)

**Comment by Tyler799** [comment]
I... had no idea those settings existed. Well darn. Thanks!

**Comment by tauSentry** [comment]
<o  

I'll go ahead and close this issue.
