### ISSUE TITLE
Community manager has head up own arse

### ISSUE THREAD

**Issue by Rusty-Bollocks** [MechWarriorOnline/issue-tracker#191]
The problem: Currently the CM just threatens to ban people for doing things PGI is too lazy to do or for offending PGI's inner circle of white knights, 

Proposal: Fire her and hire literally anyone else

**Comment by TheFifthHorseman** [comment]
This tracker does not cover manufacturing defects in the human component.

Please refer to the "non-goals" section at https://github.com/MechWarriorOnline/issue-tracker/wiki/Goals-And-Non-Goals
