### ISSUE TITLE
Multi-client crash if last remaining mech is a DC which dies.

### ISSUE THREAD

**Issue by capn-cat** [MechWarriorOnline/issue-tracker#199]
Since the recent 1.4.130 patch on 15 August I've seen this crash two times:

![Crash Image](https://i.imgur.com/3vbq4hR.jpg)

Both instances had the same parameters:
Group Queue
Last mech is a DC

At the point that the DC would have died, the game crashes for all connected players - or at least the group I was playing with who I was able to ask.

**Comment by Tarogato-MWO** [comment]
I can corroborate this crash. Happened in solo queue, last mech alive was a disconnect, we killed him with a back shot. I think it was a MAD-IIC, so I suspect the mech itself does not matter. My unit also mentioned it happening in CW when killing a disco mech when it was dropped from a dropship.

**Comment by capn-cat** [comment]
Thanks Taro. One other point of data - I'm fairly certain in both cases I got the rewards from the match, which would imply that the server stayed live and logged the results. 

Did you or your teammates notice if you received XP and CBills from your matches?

**Comment by bivant** [comment]
Happened to me a minute ago. DC mech was also MAD-IIC, was killed in the back. Quick play solo queue.

**Comment by capn-cat** [comment]
I had it happen again to me this weekend, in faction play. It was still seemingly incurred by the death of a DC mech, however on this occasion all the other pilots were still alive. So the fact that on previous occasions it was the last surviving mech may just be due to the likelihood that the a spawn DC would be the last to die.

**Comment by capn-cat** [comment]
[Potential fix for this issue in upcoming hotfix](https://mwomercs.com/news/2017/09/1896-hotfix-scheduled-for-21sep2017)

> Crash: Fixed a crash that could occur during combat when a 'Mech with no player attached was destroyed, such as when the player had disconnected.

**Comment by tauSentry** [comment]
@capn-cat, to the best of your knowledge, did this get properly handled in the hotfix?

**Comment by capn-cat** [comment]
Havent seen it since. :)
