### ISSUE TITLE
Display kill-count in all game modes

### ISSUE THREAD

**Issue by tauSentry** [MechWarriorOnline/issue-tracker#2]
* [How To Upvote This Issue](https://github.com/MechWarriorOnline/issue-tracker/wiki/How-To-Upvote-An-Issue)
* [When To Add A Comment To An Issue (vs Just Upvoting)](https://github.com/MechWarriorOnline/issue-tracker/wiki/When-To-Add-A-Comment-To-An-Issue)

---
In Domination and Conquest, players need to be able to see the current kill count. A team's strategy can be adjusted when there is information available about the number of mechs left on both teams.

Proposal: Tweak the in-game screen layout to always display the kill-count. Move the Domination timers and Conquest resource-counters elsewhere.

**Comment by muklin** [comment]
Yep, counting the white "Alive" is surprisingly taxing when concentrating on tactics.  
Heartily agree.

**Comment by Tyler799** [comment]
Yep. Information is ammunition. Knowing the remaining strength of the enemy, no matter the mode, is important to tactical decisions.

**Comment by onimusha-shin** [comment]
Upvote. It's something PGI really needs to do but has simply put off due to their current lazy coding of the kill counter display.

**Comment by hovissimo** [comment]
FWIW I feel Kill count > Alive count (or number of mechs still alive)

**Comment by tauSentry** [comment]
UPDATE:  

According to the [8-22-17 Roadmap](https://mwomercs.com/news/2017/08/1874-roadmap-for-september-october-beyond) (i.e. "Roadmap For September, October, and Beyond"), this Enhancement will be added to MWO in September!

**Comment by tauSentry** [comment]
Update:  
According to the [release notes for Patch 1.4.131 (19-Sep-2017)](https://mwomercs.com/news/2017/09/1891-patch-notes-14131-19sep2017#other), this enhancement request has been addressed.
