### ISSUE TITLE
Mist Lynx A right arm omnipod does not show energy weapon

### ISSUE THREAD

**Issue by deadskexies** [MechWarriorOnline/issue-tracker#208]
When 2 small ballistic weapons (MGs) and the hand/arm actuators are installed on the MLX-A right arm omnipod (2B 1E), non-PPC energy weapons placed in the pod are not visible. It looks like the energy hard point in this case is placed in line with the lower arm and then the hand is placed in front of the barrel. No effect in game that I've been able to tell, but it looks weird.

**Comment by tauSentry** [comment]
Administrivia...  

Can you add a screenshot(s) for clarification.

**Comment by deadskexies** [comment]
They seem to have stealth-fixed this in the new patch: As of this morning, issue no longer occurs. Go Pgi, I guess? Closing as resolved (if I can figure out how).
