### ISSUE TITLE
When opening the Skill Tree, it should jump directly to currently selected mech.

### ISSUE THREAD

**Issue by tauSentry** [MechWarriorOnline/issue-tracker#22]
... since this is the common use-case 99% of the time. More specifically, I go to the Skill Tree to unlock skills *immediately* after a match in which I earned enough XP.

Note: This may or may not be obsolete when/if the New Skill Tree gets released.

**Comment by muklin** [comment]
How do I vote this up more than once... yes yes yes!

**Comment by tauSentry** [comment]
New Skill Tree released in Patch 1.4.115 (16-May-2017), which doesn't have this issue. Closing this issue as obsolete.
