### ISSUE TITLE
Rate of heat loss quirk does NOT work

### ISSUE THREAD

**Issue by NavidA1** [MechWarriorOnline/issue-tracker#257]
Some time ago PGI introduced rate of heat loss quirks on some small mechs to compensate for their lack of dissipation due to them, not benefiting from 10 true double heatsinks in their small engines.

However, Those quirks does not seem to work at all.

To test this out, I fitted a kitfox, a mist lynx and a jenner IIC with a single ERPPC. Each of those mechs had 7 engine DHS and 6 external DHS. All unskilled.

Out of those three mechs, the jenner IIC does not have any quirks, while the other 2 have 15% rate of heat loss quirk tied to their CT pod. Also, none of those mechs have any quirks regarding weapon cooldowns.

One would expect the Kitfox and Lynx to dissipate heat more quickly compared to the jenner IIC. But private lobby tests on Canyon Network (as a map no heat offset) shows that all three dissipate the same amount of heat during weapon cooldown.

The mechs stats are:

- Base Heat capacity: 30 + 7 * 2 + 6 * 1.5 = 53.

- Base He

at dissipation: 7 * 0.2 + 6 * 0.15 = 2.3 h/s

Test: hold down trigger for a single ERPPC (14.5 heat and 4.5s cooldown)

- Heat after first fire: 14.5 ( 14.5/53 = 27% on heat bar)

- Heat after second fire: 14.5 - 2.3 * 4.5 + 14.5 = 18.65 (35%)

- Heat after third fire: 18.65 - 2.3 * 4.5 +14.5 = 22.8 (43%)

Those results exactly match what you'll see in-game as well.

I don't know if this was caused by the skill tree or not, since I did not test this before the skill tree. I also did not test this with IS mechs (such as urbie).

Would appreciate it if anyone else can confirm this. If true, this is really really messed up!

Can anyone forward this to PGI?

**Comment by tauSentry** [comment]
@Tarogato-MWO, can you give this a double check when you get a chance?

**Comment by bivant** [comment]
Somewhere on the game forums there was mention that fix for this is planned to be included into the February patch

**Comment by SaintDane01** [comment]
Issue has been fixed in a previous patch. Closing
