### ISSUE TITLE
Drop-Screen Bug "Type A": Falling Into The Void

### ISSUE THREAD

**Issue by tauSentry** [MechWarriorOnline/issue-tracker#26]
* [How To Upvote This Issue](https://github.com/MechWarriorOnline/issue-tracker/wiki/How-To-Upvote-An-Issue)
* [When To Add A Comment To An Issue (vs Just Upvoting)](https://github.com/MechWarriorOnline/issue-tracker/wiki/When-To-Add-A-Comment-To-An-Issue)

---
The dropship drops the mech through the bottom of the map. It continues to descend into the void until the dropship timer resets.

This is a major bug. It affects gameplay in a material way. A mech is kept out of the battle for up to 30 seconds.

See also: #27, #28, #132

**Comment by bivant** [comment]
I think this bug is same as "[Type B](https://github.com/MechWarriorOnline/issue-tracker/issues/27)" and behavior depends were you "spawned" inside the map or outside.

**Comment by tauSentry** [comment]
Administrivia...  
I'm hereby requesting for the community to weigh in on:  
a) if this bug continues to be an issue,  
**-OR-**  
b) if it appears to have been fixed as a side effect of fixing Issue #27 and Issue #28.

**Comment by tauSentry** [comment]
Update:

Following a 2-week period requesting confirmation (or counter-confirmation) from the community, I am marking this issue as Fixed.
