### ISSUE TITLE
Private Lobby conquest match with no captured points and all 'Mechs destroyed doesn't result in a tie

### ISSUE THREAD

**Issue by FlyingFox333** [MechWarriorOnline/issue-tracker#261]
Test BattleMech's
Two BattleMechs with identical loadouts that can reach well over 100% heat with a single alpha strike.

Replication:
1. Create a private lobby with the following parameters:
    Game Mode: Conquest
2. Select one Test BattleMech created as per above for each team
3. Launch the game
4. Both players turn on override, then simultaneously alpha strike in order to kill themselves at the same time.

The match will fail to end in a tie, and the BattleMech will be stuck in-game until the match times out.

**Comment by tauSentry** [comment]
Administrivia...

I was able to confirm the described behavior with another pilot in a Private Lobby.

On the other hand...  
_Technically_, the described behavior does agree with the official win conditions:
1. Be the first to collect 750 Resource Points (or)
2. Possess the most Resource Points when the match timer expires (or)
3. Destroy all Enemy 'Mechs and control a sufficient number of Capture Zones to guarantee a victory by Resource Points in the remaining Match Time

So, for the moment, I am going to mark this as "Works as Intended".  
(Lol, never thought I'd use that tag.)

I can always re-open it later, if needed.
