### ISSUE TITLE
text chat auto activating with custom key binding

### ISSUE THREAD

**Issue by Galenthor** [MechWarriorOnline/issue-tracker#262]
I change the default keyset so that I can use the same key for similar features cross gaming, and I have found that MWO has it so that all chat is auto active, is there any way to change this without turning off all chat? As well, the bug regarding movement stoppage keeps returning whenever I go to look at the map and want to keep moving ( autorun ) btw, I use the * key on the numpad for voip... sweet, coffeemaker is finally done...

**Comment by Michal-Gawlas** [comment]
Is this a question or a bug report? Please be aware that this is a bug tracker rather than a forum.

**Comment by tauSentry** [comment]
Closing.
