### ISSUE TITLE
Nova Breaker - Hardpoints in LA are broken - Weapon models aim 90° to the left

### ISSUE THREAD

**Issue by Blockpirat** [MechWarriorOnline/issue-tracker#271]
* [How To Upvote This Issue](https://github.com/MechWarriorOnline/issue-tracker/wiki/How-To-Upvote-An-Issue)
* [When To Add A Comment To An Issue (vs Just Upvoting)](https://github.com/MechWarriorOnline/issue-tracker/wiki/When-To-Add-A-Comment-To-An-Issue)

---

Image of the issue: https://i.imgur.com/C7MRNjK.jpg

**Comment by Larsh01** [comment]
Can confirm.  Randomly came across this on my stream yesterday.

https://youtu.be/3BQCuAwaHEw

**Comment by bivant** [comment]
This [has already been attended to](https://mwomercs.com/forums/topic/261291-breaker-nova-left-arm-working-as-intended/page__view__findpost__p__6000783) and the fix should appear in an upcoming patch.

**Comment by bivant** [comment]
Hello @tauSentry . Issue is fixed  ![screenshot](https://b.radikal.ru/b03/1802/be/c69831d604cf.jpg)
