### ISSUE TITLE
mwomercs.com Leaderboard pilot name ignores extra spaces in output

### ISSUE THREAD

**Issue by SCUR0** [MechWarriorOnline/issue-tracker#283]
* [How To Upvote This Issue](https://github.com/MechWarriorOnline/issue-tracker/wiki/How-To-Upvote-An-Issue)
* [When To Add A Comment To An Issue (vs Just Upvoting)](https://github.com/MechWarriorOnline/issue-tracker/wiki/When-To-Add-A-Comment-To-An-Issue)

---

I parse PGI's leaderboard for [The Jarl's List](https://leaderboard.isengrim.org).

Pilot names that have multiple spaces are printed the same as pilots with single space.

e.g.

Select season 4 after clicking links

https://mwomercs.com/profile/leaderboards?type=0&user=Kai+Allard-Liao

https://mwomercs.com/profile/leaderboards?type=0&user=Kai++Allard-Liao

Pilot name "Kai&nbsp;Allard-Liao" and "Kai&nbsp;&nbsp;Allard-Liao" are printed as "Kai Allard-Liao"

This causes issues with identifying pilot data in my database.

**Comment by Tarogato-MWO** [comment]
For the record, this is as simple as modifying the CSS for this table's class,

Example, 

.table-striped { white-space: pre; }

Although this could influence the many tables elsewhere on the site that use this class. It shouldn't be a problem as long as there is no incidental line breaks or extraneous spaces where they shouldn't be.

**Comment by SCUR0** [comment]
@Tarogato-MWO An easier way to fix this that shouldn't risk any issues in CSS would be to use REPLACE() in SQL or str_replace() in PHP to replace spaces with `&nbsp;` in player name output.

**Comment by SCUR0** [comment]
This can be closed as fixed. Turns out it was a html render that was showing it as not having extra spaces. Once I changed my parse script to use raw html, I am able to parse extra spaces properly.
