### ISSUE TITLE
UI shows "@ui_uiname"

### ISSUE THREAD

**Issue by RevAngel7** [MechWarriorOnline/issue-tracker#289]
![20180420_ ui_bug01](https://user-images.githubusercontent.com/38556983/39044507-a1a8f52e-4490-11e8-892b-b03fc12b0f35.jpg)
![20180420_ ui_bug02](https://user-images.githubusercontent.com/38556983/39044508-a1df0150-4490-11e8-841e-420116605230.jpg)
![20180420_ ui_bug03](https://user-images.githubusercontent.com/38556983/39044509-a20e8b14-4490-11e8-8428-44732c5cb0c5.jpg)
![20180420_ ui_bug04](https://user-images.githubusercontent.com/38556983/39044510-a23e41c4-4490-11e8-92f0-81594d135c13.jpg)
![20180420_ ui_bug05](https://user-images.githubusercontent.com/38556983/39044511-a26f7906-4490-11e8-93bb-7ad016e107bf.jpg)
![20180420_ ui_bug06](https://user-images.githubusercontent.com/38556983/39044513-a2a12b86-4490-11e8-9add-68d44271a964.jpg)

**Comment by RevAngel7** [comment]
![20180420_ ui_bug03](https://user-images.githubusercontent.com/38556983/39044476-8764bf22-4490-11e8-807b-c22cab532b62.jpg)
![20180420_ ui_bug04](https://user-images.githubusercontent.com/38556983/39044477-87950e20-4490-11e8-999e-5ce89389607d.jpg)
![20180420_ ui_bug05](https://user-images.githubusercontent.com/38556983/39044478-87c893f8-4490-11e8-95e0-664ae3ba214a.jpg)
![20180420_ ui_bug06](https://user-images.githubusercontent.com/38556983/39044479-87fc5a30-4490-11e8-97be-fea3a4648a95.jpg)
![20180420_ ui_bug01](https://user-images.githubusercontent.com/38556983/39044481-882c4d8a-4490-11e8-8f79-01972524bb2f.jpg)
![20180420_ ui_bug02](https://user-images.githubusercontent.com/38556983/39044482-88692de0-4490-11e8-832a-673be4d5c0d4.jpg)

**Comment by SaintDane01** [comment]
Are you still seeing this issue since the hotfix?

**Comment by RevAngel7** [comment]
Hi,

 

I am sorry I cannot confirm anything anymore on this ticket, because of a sudden hardware change. Please close this ticket, I will reopen a new one when the issue is still there after the rebuild of my PC.

 

Thank you!

 

Gesendet: Samstag, 21. April 2018 um 08:03 Uhr
Von: SaintDane01 <notifications@github.com>
An: MechWarriorOnline/issue-tracker <issue-tracker@noreply.github.com>
Cc: RevAngel7 <rev@pop.ms>, Author <author@noreply.github.com>
Betreff: Re: [MechWarriorOnline/issue-tracker] UI shows "@ui_uiname" (#289)


Are you still seeing this issue since the hotfix?
