### ISSUE TITLE
Scrollable In-Game Chat

### ISSUE THREAD

**Issue by tauSentry** [MechWarriorOnline/issue-tracker#29]
This is pretty low priority, but occasionally it would be useful to scroll back through recent messages that you might have missed because you were fighting at the time.

**Comment by ToastOfTheUndead** [comment]
You can use Page Up and Page Down to scroll through the In-Game Chat

**Comment by tauSentry** [comment]
Excellent!
Closing issue.

**Comment by tauSentry** [comment]
Ignore this comment.

![github reactions 1 of 3](https://cloud.githubusercontent.com/assets/27810004/26039518/c13a970c-38e9-11e7-8348-cdff37ca59c9.PNG)
![github reactions 2 of 3](https://cloud.githubusercontent.com/assets/27810004/26039519/c2a008ac-38e9-11e7-8791-7f18c907a228.PNG)
![github reactions 3 of 3](https://cloud.githubusercontent.com/assets/27810004/26039520/c4cfe610-38e9-11e7-9109-862c955637ef.PNG)
