### ISSUE TITLE
In FP Conquest, displayed cap-status is inaccurate after respawns.

### ISSUE THREAD

**Issue by tauSentry** [MechWarriorOnline/issue-tracker#31]
* [How To Upvote This Issue](https://github.com/MechWarriorOnline/issue-tracker/wiki/How-To-Upvote-An-Issue)
* [When To Add A Comment To An Issue (vs Just Upvoting)](https://github.com/MechWarriorOnline/issue-tracker/wiki/When-To-Add-A-Comment-To-An-Issue)

---
Suppose my team has 3 cap points at the moment I die. While waiting to respawn, we lose 2 caps. When I respawn I will still see my team as having 3 cap points. The display doesn't update until one of the incorrectly-displayed cap points is touched again by members of either team.

May be related to: Issue #170

**Comment by Tarogato-MWO** [comment]
This may be related to caps frequently flipping or displaying improperly while in first person Spectate mode, which is a significant issue with the Spectator Tool for Private Lobbies.

**Comment by tauSentry** [comment]
Update:  
According to the [release notes for Patch 1.4.131 (19-Sep-2017)](https://mwomercs.com/news/2017/09/1891-patch-notes-14131-19sep2017#other), this bug is supposedly fixed.
