### ISSUE TITLE
Streaks no longer lock onto turrets or generators.

### ISSUE THREAD

**Issue by tauSentry** [MechWarriorOnline/issue-tracker#32]
I have a sinking feeling that this was actually on purpose.

**Comment by ToastOfTheUndead** [comment]
This is not a bug. It was removed from the last update. Here's the link http://mwomercs.com/news/2017/04/1798-patch-notes-14111-18apr2017#other 
It's under the "Gameplay" category.

**Comment by tauSentry** [comment]
This makes tauSentry sad. :(

Closing issue.
