### ISSUE TITLE
Add Settings option to always show friendly-UAV overlay.

### ISSUE THREAD

**Issue by tauSentry** [MechWarriorOnline/issue-tracker#47]
* [How To Upvote This Issue](https://github.com/MechWarriorOnline/issue-tracker/wiki/How-To-Upvote-An-Issue)
* [When To Add A Comment To An Issue (vs Just Upvoting)](https://github.com/MechWarriorOnline/issue-tracker/wiki/When-To-Add-A-Comment-To-An-Issue)

---
No one likes having to leave up an enemy uav any longer than necessary. Having to press 'Q' to check is a waste of time.

Note: This is separate from issue #38.

See also: Issue #236

**Comment by Tarogato-MWO** [comment]
Would recommend actually reverting the change so that friendly UAVs are *never* hidden.

**Comment by tauSentry** [comment]
Update:  
According to the [release notes for Patch 1.4.132 (17-Oct-2017)](https://mwomercs.com/news/2017/10/1910-patch-notes-14132-17oct2017), this feature request has been made obsolete because friendly UAV markers are being restored. See Issue #236.

@Tarogato-MWO, you got your wish! :D
