### ISSUE TITLE
Double Click removes weapons, equipment, etc. Double click does not remove Modules. 

### ISSUE THREAD

**Issue by muklin** [MechWarriorOnline/issue-tracker#54]
* [How To Upvote This Issue](https://github.com/MechWarriorOnline/issue-tracker/wiki/How-To-Upvote-An-Issue)
* [When To Add A Comment To An Issue (vs Just Upvoting)](https://github.com/MechWarriorOnline/issue-tracker/wiki/When-To-Add-A-Comment-To-An-Issue)

---
Potentially a short lived issue, since Modules are headed for the Junk Heap (in Canyon.)  But I keep double clicking my modules expecting them to be unequipped.  This works for Weapons, but not for Modules.  Why?

**Comment by tauSentry** [comment]
Closing and marking as Obsolete since Modules are not in the new Skill Tree.
