### ISSUE TITLE
Allow sorting & filtering of Skills by IS/Clan, Missile/Ballistic/Laser, "Currently Equipped", etc.

### ISSUE THREAD

**Issue by muklin** [MechWarriorOnline/issue-tracker#55]
* [How To Upvote This Issue](https://github.com/MechWarriorOnline/issue-tracker/wiki/How-To-Upvote-An-Issue)
* [When To Add A Comment To An Issue (vs Just Upvoting)](https://github.com/MechWarriorOnline/issue-tracker/wiki/When-To-Add-A-Comment-To-An-Issue)

---
Another issue that is slated for redundancy, should Skill tree make it to production.  

Currently, there is no clear sorting to the GXP purchasable weapon skills, and indeed I believe it changes every time you open it.  (I don't understand how this even happens.  CRINGE.) 

At the very least, make it sortable by IS/Clan, and enable a list view option.

**Comment by tauSentry** [comment]
Administrivia...
Is this still an issue in the released Skill Tree?

**Comment by muklin** [comment]
Yes, still an issue...

**Comment by tauSentry** [comment]
Administrivia...

Can you update the original description to describe how it relates to the new skill tree.  
Maybe even upload a few screenshots or mockups to help voters better understand what you're proposing.

**Comment by muklin** [comment]
This is actually resolved with Skill tree.  don't know what my 29/May comment was thinking.
