### ISSUE TITLE
Unsupported gamemodes on maps greatly reduce the probability of certain maps appearing

### ISSUE THREAD

**Issue by Shivaran** [MechWarriorOnline/issue-tracker#63]
The introduction of Escort and Incursion, gamemodes available to only a portion of the totals maps, have greatly reduced the probability of certain maps appearing (e.g. Terra Therma...).

When a gamemode is available in the selection, only maps supporting it are available, meaning maps not supporting those two gamemodes are available less often than those supporting it.

There are several options to improve the situation that came to my mind : 
- Make all maps compatible to all modes (obviously...)
- Remove the gamemode selection and integrate it in the map selection, meaning we would choose for one combination instead of two separate option (e.g. Alpine/Domi VS Caustic/Skirmish VS Viridian/Domi VS TerraTherma/Conquest ...)
- Modify the map weights to make rarer maps appear more frequently when then can according to gamemodes available (possibly making it dynamic?)
- Remove the map selection altogether, leaving only gamemode selection and have the map random

EDIT:
This issue is now separated into: #65, #66, #67.

**Comment by tauSentry** [comment]
Hi @Shivaran. Thanks for contributing!

I recommend that you create separate issues for suggestions 2-4, so that members of the community can vote for each separately - one of which should emerge as the community-preferred solution. This is certainly something the community as a whole would like to see addressed.

Once those are up, I'll close this one and then cross-link all four.

**Comment by tauSentry** [comment]
Closing this now that it has been separated into: #65, #66, #67.

**Comment by tauSentry** [comment]
Btw @Shivaran, to give this topic even more attention and encourage people to vote for their preferred solution, you might consider posting to the MWO forum and to the MWO subreddits ([/r/mwo/](https://www.reddit.com/r/mwo/) and [/r/OutreachHPG/](https://www.reddit.com/r/OutreachHPG/)), including links to each proposal for convenience.
