### ISSUE TITLE
Thought: In Siege Mode, give the faction-being-invaded the benefit of defending the base every match.

### ISSUE THREAD

**Issue by tauSentry** [MechWarriorOnline/issue-tracker#75]
* [How To Upvote This Issue](https://github.com/MechWarriorOnline/issue-tracker/wiki/How-To-Upvote-An-Issue)
* [When To Add A Comment To An Issue (vs Just Upvoting)](https://github.com/MechWarriorOnline/issue-tracker/wiki/When-To-Add-A-Comment-To-An-Issue)

---

Note: This might turn out to be too controversial a topic for this issue tracker. If that ends up being the case, I will close the issue since this issue tracker is intended for issues that are not divisive in the community. Please refer to the [*Goals* and *Non-Goals*](https://github.com/MechWarriorOnline/issue-tracker) of this issue tracker.

---
**For some time now, I've been hearing this idea kicked around over voice-coms during matches - usually during ROFLstomps. Given the recent Tukayyid 3 event. I figured I would place it in view of the community so it could be voted on. I claim no credit for this idea; it's not new.**

*Disclaimer: I was part of the invading force on Tukayyid 3.*

The Faction Play maps typically favor the defenders. In addition to the defending mechs, the attackers also have to contend with: longer travel time from spawn, gate turrets, gate generators, base turrets, base generators, and Omega.

By the time that the Invasion Slider has moved to Siege Mode, it's often clear that the invaders have one or more advantages (e.g. more pilots online at that time, more mercs under contract, etc., etc.). The invad*ees* need all the help they can get against the invaders. At this point in an attack cycle, the invad*ees* can often be left feeling a little demoralized. It's not uncommon for some pilots in the losing faction to just take a break from MWO and wait for the next attack cycle. The pilots who remain behind to fight can get even more demoralized when having to attack a well-defended base.

ROFLstomps are always a possibility. There is no remedy for that. However, this might be a reasonable place to intervene. The community can decide for itself...

**Proposal: In Siege Mode, make the invading faction always have to attack the base, giving the being-invaded faction a little extra help.**

I'll be the first to admit that I don't know all the possible ramifications of such a change. That being the case, I've added the "Public Feedback Welcome" and "More Information Needed" tags to encourage some additional *objective* information about the possible consequences.

**Comment by wraith31** [comment]
Nope

**Comment by tauSentry** [comment]
Reminder: Only leave a comment if you have something substantive to add to the discussion.
Things like: "+1", "-1", "Yes!", "Nope", will be removed.

**Comment by wraith31** [comment]
On a thread asking a yes/no question?  Really?

**Comment by tauSentry** [comment]
Closing as "Withdrawn".
