### ISSUE TITLE
Nova left arm is misaligned

### ISSUE THREAD

**Issue by Tarogato-MWO** [MechWarriorOnline/issue-tracker#76]
* [How To Upvote This Issue](https://github.com/MechWarriorOnline/issue-tracker/wiki/How-To-Upvote-An-Issue)
* [When To Add A Comment To An Issue (vs Just Upvoting)](https://github.com/MechWarriorOnline/issue-tracker/wiki/When-To-Add-A-Comment-To-An-Issue)

---
Example:  
![](http://i.imgur.com/la0pxI3.jpg)

**Comment by tauSentry** [comment]
According to the [Release Notes for Patch 1.4.143 (12-Dec-2017)](https://mwomercs.com/news/2017/12/1969-patch-notes-14143-12dec2017), this has been fixed.
