### ISSUE TITLE
Join Group error...

### ISSUE THREAD

**Issue by CyberDashie** [MechWarriorOnline/issue-tracker#81]
* [How To Upvote This Issue](https://github.com/MechWarriorOnline/issue-tracker/wiki/How-To-Upvote-An-Issue)

---

I was in a group for Scouting with no issue. The event just ended and I can not pull the group box up in my friends list or messages. 

I tried to join a Unit member's group and it said "Currently already in a group of this type."

https://cdn.discordapp.com/attachments/273888373876457472/313443470410776578/unknown.png

I also tried creating a group of my own and it gave me the same error.

~CyberDashie

**Comment by tauSentry** [comment]
This seems to have been fixed in Patch 1.4.115 (16-May02017).
